### ISSUE TITLE
threat increase and decrease expression malfunction on non-player entity

### ISSUE THREAD

**Issue by f-ly** [BerndiVader/mmSkriptAddon#2]
server version: git-Paper-1414
mythicmobs version: v4.3.2-SNAPSHOT
mmSkriptAddon version: v0.92a
skript version: v2.2-dev36

```
inc threat of %entity% by %number% from activemob %activemob%
dec threat of %entity by %number% from activemob %activemob%
```

The following two expressions do not work when the entity is not a player.
The code that was tested:
```
on mythicmobs skriptskillevent:
	if skill-name is "UltStr_autoThreat":
		set {_am} to event-activemob
		set {_p} to owner of activemob {_am}
		set {_loc} to location of activemob {_am}
		loop entities in radius 30 of {_loc}:
			loop-entity instanceof activemob
			set {_am} to activemob of loop-entity
			owner of activemob {_am} is not set
			tamer of loop-entity is not set
			broadcast "aggroIncrease: %loop-entity%"
			inc threat of loop-entity by 100 from activemob {_am} #<----Try this with any entity
```

**I think this should be a bit more straightforward**
```
on mythicmobs skriptskillevent:
	if skill-name is "UltStr_Threat":
		set {_am} to event-activemob
		set {_loc} to location of activemob {_am}
		loop entities in radius 30 of {_loc}:
			inc threat of loop-entity by 100 from activemob {_am} #<----Try this with any entity
```

**Comment by BerndiVader** [comment]
Hi! Thanks for reporting. The threattable works for all living entities that are not the owner or the activemob itself. At first glance, i think the issue is in your skript.

In the party statement: 
`inc threat of {_am_entity} by {_bossAggro} from activemob {_am}`
you try to increase the threat for `{_am_entity}` but this temp variable is never set.

In the radius 30 loop you renew the `{_am}` from the first line of the skill with the activemob instance of the loop-entity (if present) in the last line you try to increase the threat of the loop-entity for the activemob isntance of the loop-entity.

You maybe fix this by setting the `{_am_boss_entity}` in the partystatement and by removing or renaming the `set {_am} to activemob of loop-entity`

**Comment by f-ly** [comment]
Thank you for your quick response.
I've edited the code to put light on what really was the problem at hand.
Simply, increasing threat for non-entity players do not work.
Sorry for adding useless code that probably was the source for the confusion.

KST(18/06/21 16:55) -> just double-checked, it definitely doesn't work

**Comment by BerndiVader** [comment]
Hello fly! Here is how i tested it: 

```
SkriptMonkey:
  Type: zombie
  Display: "SkriptMonkey"
  Health: 20
  Modules:
    ThreatTable: true
  Skills:
  - skriptskill{s=threattest} @trigger ~onInteract
  
on mythicmobs skriptskillevent:
	if skill-name is "threattest":
		set {_am} to event-activemob
		set {_loc} to location of activemob {_am}
		loop living entities in radius 30 of {_loc}:
			inc threat of loop-entity by 100 from activemob {_am}
		set {_tt::*} to get threattable of activemob {_am}
		loop {_tt::*}:
			set {_e} to loop-value
			set {_v} to get threatvalue of {_e} from activemob {_am}
			broadcast "%{_e}% with value %{_v}%"
```
I spawned 2 pigs, 3 villagers, 2 skeletons and that mythicmob. After right clicking the mob it spammed me all the entities including myself. Can you try that skript and mob above?

**Comment by f-ly** [comment]
Really sorry for wasting your time,
I made the mistake of declaring {_am} as the same mythicmob as the looped-entity
Thanks for helping out.
